[build]
  functions = "./functions"

[[headers]]
  for = "/*.js"
  [headers.values]
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: same-origin

  for = "/*.js"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''

  for = "/*.css"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''

  for = "/fonts/*"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''

  for = "/img/*"
  [headers.values]
	cache-control = '''
	public,
	max-age=86400,
	stale-while-revalidate=86400'''
